
#|

c2ffi /usr/include/SDL2/SDL_image.h > h 

add javascript to parse json file

change h script to make "libSDL2_image" in foreign-library-function call

autogenerated from nodejs using h 


|#

;; definition 6887 from /usr/include/SDL2/SDL_image.h:167:29
(define IMG-Init
   (foreign-library-function "libSDL2_image" "IMG_Init" 
     #:return-type int       #:arg-types (int ))


;; definition 6889 from /usr/include/SDL2/SDL_image.h:253:39
(define IMG-LoadTyped-RW
   (foreign-library-function "libSDL2_image" "IMG_LoadTyped_RW" 
     #:return-type '*       #:arg-types ('* int '* ))


;; definition 6890 from /usr/include/SDL2/SDL_image.h:295:39
(define IMG-Load
   (foreign-library-function "libSDL2_image" "IMG_Load" 
     #:return-type '*       #:arg-types ('* ))


;; definition 6891 from /usr/include/SDL2/SDL_image.h:348:39
(define IMG-Load-RW
   (foreign-library-function "libSDL2_image" "IMG_Load_RW" 
     #:return-type '*       #:arg-types ('* int ))


;; definition 6892 from /usr/include/SDL2/SDL_image.h:386:39
(define IMG-LoadTexture
   (foreign-library-function "libSDL2_image" "IMG_LoadTexture" 
     #:return-type '*       #:arg-types ('* '* ))


;; definition 6893 from /usr/include/SDL2/SDL_image.h:433:39
(define IMG-LoadTexture-RW
   (foreign-library-function "libSDL2_image" "IMG_LoadTexture_RW" 
     #:return-type '*       #:arg-types ('* '* int ))


;; definition 6894 from /usr/include/SDL2/SDL_image.h:488:39
(define IMG-LoadTextureTyped-RW
   (foreign-library-function "libSDL2_image" "IMG_LoadTextureTyped_RW" 
     #:return-type '*       #:arg-types ('* '* int '* ))


;; definition 6895 from /usr/include/SDL2/SDL_image.h:533:29
(define IMG-isAVIF
   (foreign-library-function "libSDL2_image" "IMG_isAVIF" 
     #:return-type int       #:arg-types ('* ))


;; definition 6896 from /usr/include/SDL2/SDL_image.h:576:29
(define IMG-isICO
   (foreign-library-function "libSDL2_image" "IMG_isICO" 
     #:return-type int       #:arg-types ('* ))


;; definition 6897 from /usr/include/SDL2/SDL_image.h:619:29
(define IMG-isCUR
   (foreign-library-function "libSDL2_image" "IMG_isCUR" 
     #:return-type int       #:arg-types ('* ))


;; definition 6898 from /usr/include/SDL2/SDL_image.h:662:29
(define IMG-isBMP
   (foreign-library-function "libSDL2_image" "IMG_isBMP" 
     #:return-type int       #:arg-types ('* ))


;; definition 6899 from /usr/include/SDL2/SDL_image.h:705:29
(define IMG-isGIF
   (foreign-library-function "libSDL2_image" "IMG_isGIF" 
     #:return-type int       #:arg-types ('* ))


;; definition 6900 from /usr/include/SDL2/SDL_image.h:748:29
(define IMG-isJPG
   (foreign-library-function "libSDL2_image" "IMG_isJPG" 
     #:return-type int       #:arg-types ('* ))


;; definition 6901 from /usr/include/SDL2/SDL_image.h:791:29
(define IMG-isJXL
   (foreign-library-function "libSDL2_image" "IMG_isJXL" 
     #:return-type int       #:arg-types ('* ))


;; definition 6902 from /usr/include/SDL2/SDL_image.h:834:29
(define IMG-isLBM
   (foreign-library-function "libSDL2_image" "IMG_isLBM" 
     #:return-type int       #:arg-types ('* ))


;; definition 6903 from /usr/include/SDL2/SDL_image.h:877:29
(define IMG-isPCX
   (foreign-library-function "libSDL2_image" "IMG_isPCX" 
     #:return-type int       #:arg-types ('* ))


;; definition 6904 from /usr/include/SDL2/SDL_image.h:920:29
(define IMG-isPNG
   (foreign-library-function "libSDL2_image" "IMG_isPNG" 
     #:return-type int       #:arg-types ('* ))


;; definition 6905 from /usr/include/SDL2/SDL_image.h:963:29
(define IMG-isPNM
   (foreign-library-function "libSDL2_image" "IMG_isPNM" 
     #:return-type int       #:arg-types ('* ))


;; definition 6906 from /usr/include/SDL2/SDL_image.h:1006:29
(define IMG-isSVG
   (foreign-library-function "libSDL2_image" "IMG_isSVG" 
     #:return-type int       #:arg-types ('* ))


;; definition 6907 from /usr/include/SDL2/SDL_image.h:1049:29
(define IMG-isQOI
   (foreign-library-function "libSDL2_image" "IMG_isQOI" 
     #:return-type int       #:arg-types ('* ))


;; definition 6908 from /usr/include/SDL2/SDL_image.h:1092:29
(define IMG-isTIF
   (foreign-library-function "libSDL2_image" "IMG_isTIF" 
     #:return-type int       #:arg-types ('* ))


;; definition 6909 from /usr/include/SDL2/SDL_image.h:1135:29
(define IMG-isXCF
   (foreign-library-function "libSDL2_image" "IMG_isXCF" 
     #:return-type int       #:arg-types ('* ))


;; definition 6910 from /usr/include/SDL2/SDL_image.h:1178:29
(define IMG-isXPM
   (foreign-library-function "libSDL2_image" "IMG_isXPM" 
     #:return-type int       #:arg-types ('* ))


;; definition 6911 from /usr/include/SDL2/SDL_image.h:1221:29
(define IMG-isXV
   (foreign-library-function "libSDL2_image" "IMG_isXV" 
     #:return-type int       #:arg-types ('* ))


;; definition 6912 from /usr/include/SDL2/SDL_image.h:1264:29
(define IMG-isWEBP
   (foreign-library-function "libSDL2_image" "IMG_isWEBP" 
     #:return-type int       #:arg-types ('* ))


;; definition 6913 from /usr/include/SDL2/SDL_image.h:1298:39
(define IMG-LoadAVIF-RW
   (foreign-library-function "libSDL2_image" "IMG_LoadAVIF_RW" 
     #:return-type '*       #:arg-types ('* ))


;; definition 6914 from /usr/include/SDL2/SDL_image.h:1332:39
(define IMG-LoadICO-RW
   (foreign-library-function "libSDL2_image" "IMG_LoadICO_RW" 
     #:return-type '*       #:arg-types ('* ))


;; definition 6915 from /usr/include/SDL2/SDL_image.h:1366:39
(define IMG-LoadCUR-RW
   (foreign-library-function "libSDL2_image" "IMG_LoadCUR_RW" 
     #:return-type '*       #:arg-types ('* ))


;; definition 6916 from /usr/include/SDL2/SDL_image.h:1400:39
(define IMG-LoadBMP-RW
   (foreign-library-function "libSDL2_image" "IMG_LoadBMP_RW" 
     #:return-type '*       #:arg-types ('* ))


;; definition 6917 from /usr/include/SDL2/SDL_image.h:1434:39
(define IMG-LoadGIF-RW
   (foreign-library-function "libSDL2_image" "IMG_LoadGIF_RW" 
     #:return-type '*       #:arg-types ('* ))


;; definition 6918 from /usr/include/SDL2/SDL_image.h:1468:39
(define IMG-LoadJPG-RW
   (foreign-library-function "libSDL2_image" "IMG_LoadJPG_RW" 
     #:return-type '*       #:arg-types ('* ))


;; definition 6919 from /usr/include/SDL2/SDL_image.h:1502:39
(define IMG-LoadJXL-RW
   (foreign-library-function "libSDL2_image" "IMG_LoadJXL_RW" 
     #:return-type '*       #:arg-types ('* ))


;; definition 6920 from /usr/include/SDL2/SDL_image.h:1536:39
(define IMG-LoadLBM-RW
   (foreign-library-function "libSDL2_image" "IMG_LoadLBM_RW" 
     #:return-type '*       #:arg-types ('* ))


;; definition 6921 from /usr/include/SDL2/SDL_image.h:1570:39
(define IMG-LoadPCX-RW
   (foreign-library-function "libSDL2_image" "IMG_LoadPCX_RW" 
     #:return-type '*       #:arg-types ('* ))


;; definition 6922 from /usr/include/SDL2/SDL_image.h:1604:39
(define IMG-LoadPNG-RW
   (foreign-library-function "libSDL2_image" "IMG_LoadPNG_RW" 
     #:return-type '*       #:arg-types ('* ))


;; definition 6923 from /usr/include/SDL2/SDL_image.h:1638:39
(define IMG-LoadPNM-RW
   (foreign-library-function "libSDL2_image" "IMG_LoadPNM_RW" 
     #:return-type '*       #:arg-types ('* ))


;; definition 6924 from /usr/include/SDL2/SDL_image.h:1672:39
(define IMG-LoadSVG-RW
   (foreign-library-function "libSDL2_image" "IMG_LoadSVG_RW" 
     #:return-type '*       #:arg-types ('* ))


;; definition 6925 from /usr/include/SDL2/SDL_image.h:1706:39
(define IMG-LoadQOI-RW
   (foreign-library-function "libSDL2_image" "IMG_LoadQOI_RW" 
     #:return-type '*       #:arg-types ('* ))


;; definition 6926 from /usr/include/SDL2/SDL_image.h:1740:39
(define IMG-LoadTGA-RW
   (foreign-library-function "libSDL2_image" "IMG_LoadTGA_RW" 
     #:return-type '*       #:arg-types ('* ))


;; definition 6927 from /usr/include/SDL2/SDL_image.h:1774:39
(define IMG-LoadTIF-RW
   (foreign-library-function "libSDL2_image" "IMG_LoadTIF_RW" 
     #:return-type '*       #:arg-types ('* ))


;; definition 6928 from /usr/include/SDL2/SDL_image.h:1808:39
(define IMG-LoadXCF-RW
   (foreign-library-function "libSDL2_image" "IMG_LoadXCF_RW" 
     #:return-type '*       #:arg-types ('* ))


;; definition 6929 from /usr/include/SDL2/SDL_image.h:1842:39
(define IMG-LoadXPM-RW
   (foreign-library-function "libSDL2_image" "IMG_LoadXPM_RW" 
     #:return-type '*       #:arg-types ('* ))


;; definition 6930 from /usr/include/SDL2/SDL_image.h:1876:39
(define IMG-LoadXV-RW
   (foreign-library-function "libSDL2_image" "IMG_LoadXV_RW" 
     #:return-type '*       #:arg-types ('* ))


;; definition 6931 from /usr/include/SDL2/SDL_image.h:1910:39
(define IMG-LoadWEBP-RW
   (foreign-library-function "libSDL2_image" "IMG_LoadWEBP_RW" 
     #:return-type '*       #:arg-types ('* ))


;; definition 6932 from /usr/include/SDL2/SDL_image.h:1931:39
(define IMG-LoadSizedSVG-RW
   (foreign-library-function "libSDL2_image" "IMG_LoadSizedSVG_RW" 
     #:return-type '*       #:arg-types ('* int int ))


;; definition 6933 from /usr/include/SDL2/SDL_image.h:1950:39
(define IMG-ReadXPMFromArray
   (foreign-library-function "libSDL2_image" "IMG_ReadXPMFromArray" 
     #:return-type '*       #:arg-types ('* ))


;; definition 6934 from /usr/include/SDL2/SDL_image.h:1969:39
(define IMG-ReadXPMFromArrayToRGB888
   (foreign-library-function "libSDL2_image" "IMG_ReadXPMFromArrayToRGB888" 
     #:return-type '*       #:arg-types ('* ))


;; definition 6935 from /usr/include/SDL2/SDL_image.h:1986:29
(define IMG-SavePNG
   (foreign-library-function "libSDL2_image" "IMG_SavePNG" 
     #:return-type int       #:arg-types ('* '* ))


;; definition 6936 from /usr/include/SDL2/SDL_image.h:2003:29
(define IMG-SavePNG-RW
   (foreign-library-function "libSDL2_image" "IMG_SavePNG_RW" 
     #:return-type int       #:arg-types ('* '* int ))


;; definition 6937 from /usr/include/SDL2/SDL_image.h:2022:29
(define IMG-SaveJPG
   (foreign-library-function "libSDL2_image" "IMG_SaveJPG" 
     #:return-type int       #:arg-types ('* '* int ))


;; definition 6938 from /usr/include/SDL2/SDL_image.h:2039:29
(define IMG-SaveJPG-RW
   (foreign-library-function "libSDL2_image" "IMG_SaveJPG_RW" 
     #:return-type int       #:arg-types ('* '* int int ))


;; definition 6941 from /usr/include/SDL2/SDL_image.h:2067:41
(define IMG-LoadAnimation
   (foreign-library-function "libSDL2_image" "IMG_LoadAnimation" 
     #:return-type '*       #:arg-types ('* ))


;; definition 6942 from /usr/include/SDL2/SDL_image.h:2088:41
(define IMG-LoadAnimation-RW
   (foreign-library-function "libSDL2_image" "IMG_LoadAnimation_RW" 
     #:return-type '*       #:arg-types ('* int ))


;; definition 6943 from /usr/include/SDL2/SDL_image.h:2118:41
(define IMG-LoadAnimationTyped-RW
   (foreign-library-function "libSDL2_image" "IMG_LoadAnimationTyped_RW" 
     #:return-type '*       #:arg-types ('* int '* ))


;; definition 6944 from /usr/include/SDL2/SDL_image.h:2133:30
(define IMG-FreeAnimation
   (foreign-library-function "libSDL2_image" "IMG_FreeAnimation" 
     #:return-type void       #:arg-types ('* ))


;; definition 6945 from /usr/include/SDL2/SDL_image.h:2153:41
(define IMG-LoadGIFAnimation-RW
   (foreign-library-function "libSDL2_image" "IMG_LoadGIFAnimation_RW" 
     #:return-type '*       #:arg-types ('* ))


;; definition 6946 from /usr/include/SDL2/SDL_image.h:2173:41
(define IMG-LoadWEBPAnimation-RW
   (foreign-library-function "libSDL2_image" "IMG_LoadWEBPAnimation_RW" 
     #:return-type '*       #:arg-types ('* ))
