;; autogenerated file from documentation sdl.org file via emacs

(define-module (graphics sdl2)
  #:export (*sdl-init-timer*
	    *sdl-init-audio*
	    *sdl-init-video*
	    *sdl-init-joystick*
	    *sdl-init-haptic*
	    *sdl-init-gamecontroller*
	    *sdl-init-events*
	    *sdl-init-sensor*
	    *sdl-init-parachute*
	    *sdl-init-everything*

	    *sdl-pixelformat-argb8888*
	    *sdl-texture-streaming*
				   
	    sdl-init
	    sdl-quit

	    *cairo-operator-source*
	    
	    cairo-identity-matrix
	    cairo-translate
	    cairo-scale
	    
cairo-set-operator	    
cairo-paint
cairo-surface-destroy	    
sdl-create-window
create-window
sdl-get-window-surface
sdl-free-surface
sdl-load-bmp-rw
sdl-rw-from-file
sdl-load-bmp
sdl-show-cursor
load-texture
img-quit
sdl-destroy-window

sdl-lock-surface
sdl-unlock-surface


sdl-get-window-size
sdl-get-renderer-output-size

sanity-check-hack ;; <<<<< 

sdl-create-texture-from-surface
sdl-create-texture
sdl-destroy-texture
sdl-destroy-renderer

sdl-get-pixelformat-name
create-rgb24-surface
create-argb32-surface
sdl-create-rgb-surface

sdl-map-rgb
sdl-fill-rect
sdl-update-texture
sdl-update-window-surface
sdl-convert-surface
sdl-blit-surface
sdl-render-clear
sdl-render-copy
sdl-render-present
sdl-render-draw-line
sdl-render-draw-rect
sdl-render-fill-rect
sdl-render-draw-point

sdl-poll-event

*sdl-quit*
*sdl-keydown*
*sdl-keyup*
*sdl-mousemotion*
*sdl-window-event*
*sdl-scancode-unknown* 
*sdl-scancode-a* 
*sdl-scancode-b* 
*sdl-scancode-c* 
*sdl-scancode-d* 
*sdl-scancode-e* 
*sdl-scancode-f* 
*sdl-scancode-g* 
*sdl-scancode-h* 
*sdl-scancode-i* 
*sdl-scancode-j* 
*sdl-scancode-k* 
*sdl-scancode-l* 
*sdl-scancode-m* 
*sdl-scancode-n* 
*sdl-scancode-o* 
*sdl-scancode-p* 
*sdl-scancode-q* 
*sdl-scancode-r* 
*sdl-scancode-s* 
*sdl-scancode-t* 
*sdl-scancode-u* 
*sdl-scancode-v* 
*sdl-scancode-w* 
*sdl-scancode-x* 
*sdl-scancode-y* 
*sdl-scancode-z* 
*sdl-scancode-1* 
*sdl-scancode-2* 
*sdl-scancode-3* 
*sdl-scancode-4* 
*sdl-scancode-5* 
*sdl-scancode-6* 
*sdl-scancode-7* 
*sdl-scancode-8* 
*sdl-scancode-9* 
*sdl-scancode-0* 
*sdl-scancode-return* 
*sdl-scancode-escape* 
*sdl-scancode-backspace* 
*sdl-scancode-tab* 
*sdl-scancode-space* 
*sdl-scancode-minus* 
*sdl-scancode-equals* 
*sdl-scancode-leftbracket* 
*sdl-scancode-rightbracket* 
*sdl-scancode-backslash* 
*sdl-scancode-nonushash* 
*sdl-scancode-semicolon* 
*sdl-scancode-apostrophe* 
*sdl-scancode-grave* 
*sdl-scancode-comma* 
*sdl-scancode-period* 
*sdl-scancode-slash* 
*sdl-scancode-capslock* 
*sdl-scancode-f1* 
*sdl-scancode-f2* 
*sdl-scancode-f3* 
*sdl-scancode-f4* 
*sdl-scancode-f5* 
*sdl-scancode-f6* 
*sdl-scancode-f7* 
*sdl-scancode-f8* 
*sdl-scancode-f9* 
*sdl-scancode-f10* 
*sdl-scancode-f11* 
*sdl-scancode-f12* 
*sdl-scancode-printscreen* 
*sdl-scancode-scrolllock* 
*sdl-scancode-pause* 
*sdl-scancode-insert* 
*sdl-scancode-home* 
*sdl-scancode-pageup* 
*sdl-scancode-delete* 
*sdl-scancode-end* 
*sdl-scancode-pagedown* 
*sdl-scancode-right* 
*sdl-scancode-left* 
*sdl-scancode-down* 
*sdl-scancode-up* 
*sdl-scancode-numlockclear* 
*sdl-scancode-kp-divide* 
*sdl-scancode-kp-multiply* 
*sdl-scancode-kp-minus* 
*sdl-scancode-kp-plus* 
*sdl-scancode-kp-enter* 
*sdl-scancode-kp-1* 
*sdl-scancode-kp-2* 
*sdl-scancode-kp-3* 
*sdl-scancode-kp-4* 
*sdl-scancode-kp-5* 
*sdl-scancode-kp-6* 
*sdl-scancode-kp-7* 
*sdl-scancode-kp-8* 
*sdl-scancode-kp-9* 
*sdl-scancode-kp-0* 
*sdl-scancode-kp-period* 
*sdl-scancode-nonusbackslash* 
*sdl-scancode-application* 
*sdl-scancode-power* 
*sdl-scancode-kp-equals* 
*sdl-scancode-f13* 
*sdl-scancode-f14* 
*sdl-scancode-f15* 
*sdl-scancode-f16* 
*sdl-scancode-f17* 
*sdl-scancode-f18* 
*sdl-scancode-f19* 
*sdl-scancode-f20* 
*sdl-scancode-f21* 
*sdl-scancode-f22* 
*sdl-scancode-f23* 
*sdl-scancode-f24* 
*sdl-scancode-execute* 
*sdl-scancode-help* 
*sdl-scancode-menu* 
*sdl-scancode-select* 
*sdl-scancode-stop* 
*sdl-scancode-again* 
*sdl-scancode-undo* 
*sdl-scancode-cut* 
*sdl-scancode-copy* 
*sdl-scancode-paste* 
*sdl-scancode-find* 
*sdl-scancode-mute* 
*sdl-scancode-volumeup* 
*sdl-scancode-volumedown* 
*sdl-scancode-lockingcapslock* 
*sdl-scancode-lockingnumlock* 
*sdl-scancode-lockingscrolllock* 
*sdl-scancode-kp-comma* 
*sdl-scancode-kp-equalsas400* 
*sdl-scancode-international1* 
*sdl-scancode-international2* 
*sdl-scancode-international3* 
*sdl-scancode-international4* 
*sdl-scancode-international5* 
*sdl-scancode-international6* 
*sdl-scancode-international7* 
*sdl-scancode-international8* 
*sdl-scancode-international9* 
*sdl-scancode-lang1* 
*sdl-scancode-lang2* 
*sdl-scancode-lang3* 
*sdl-scancode-lang4* 
*sdl-scancode-lang5* 
*sdl-scancode-lang6* 
*sdl-scancode-lang7* 
*sdl-scancode-lang8* 
*sdl-scancode-lang9* 
*sdl-scancode-alterase* 
*sdl-scancode-sysreq* 
*sdl-scancode-cancel* 
*sdl-scancode-clear* 
*sdl-scancode-prior* 
*sdl-scancode-return2* 
*sdl-scancode-separator* 
*sdl-scancode-out* 
*sdl-scancode-oper* 
*sdl-scancode-clearagain* 
*sdl-scancode-crsel* 
*sdl-scancode-exsel* 
*sdl-scancode-kp-00* 
*sdl-scancode-kp-000* 
*sdl-scancode-thousandsseparator* 
*sdl-scancode-decimalseparator* 
*sdl-scancode-currencyunit* 
*sdl-scancode-currencysubunit* 
*sdl-scancode-kp-leftparen* 
*sdl-scancode-kp-rightparen* 
*sdl-scancode-kp-leftbrace* 
*sdl-scancode-kp-rightbrace* 
*sdl-scancode-kp-tab* 
*sdl-scancode-kp-backspace* 
*sdl-scancode-kp-a* 
*sdl-scancode-kp-b* 
*sdl-scancode-kp-c* 
*sdl-scancode-kp-d* 
*sdl-scancode-kp-e* 
*sdl-scancode-kp-f* 
*sdl-scancode-kp-xor* 
*sdl-scancode-kp-power* 
*sdl-scancode-kp-percent* 
*sdl-scancode-kp-less* 
*sdl-scancode-kp-greater* 
*sdl-scancode-kp-ampersand* 
*sdl-scancode-kp-dblampersand* 
*sdl-scancode-kp-verticalbar* 
*sdl-scancode-kp-dblverticalbar* 
*sdl-scancode-kp-colon* 
*sdl-scancode-kp-hash* 
*sdl-scancode-kp-space* 
*sdl-scancode-kp-at* 
*sdl-scancode-kp-exclam* 
*sdl-scancode-kp-memstore* 
*sdl-scancode-kp-memrecall* 
*sdl-scancode-kp-memclear* 
*sdl-scancode-kp-memadd* 
*sdl-scancode-kp-memsubtract* 
*sdl-scancode-kp-memmultiply* 
*sdl-scancode-kp-memdivide* 
*sdl-scancode-kp-plusminus* 
*sdl-scancode-kp-clear* 
*sdl-scancode-kp-clearentry* 
*sdl-scancode-kp-binary* 
*sdl-scancode-kp-octal* 
*sdl-scancode-kp-decimal* 
*sdl-scancode-kp-hexadecimal* 
*sdl-scancode-lctrl* 
*sdl-scancode-lshift* 
*sdl-scancode-lalt* 
*sdl-scancode-lgui* 
*sdl-scancode-rctrl* 
*sdl-scancode-rshift* 
*sdl-scancode-ralt* 
*sdl-scancode-rgui* 
*sdl-scancode-mode* 
*sdl-scancode-audionext* 
*sdl-scancode-audioprev* 
*sdl-scancode-audiostop* 
*sdl-scancode-audioplay* 
*sdl-scancode-audiomute* 
*sdl-scancode-mediaselect* 
*sdl-scancode-www* 
*sdl-scancode-mail* 
*sdl-scancode-calculator* 
*sdl-scancode-computer* 
*sdl-scancode-ac-search* 
*sdl-scancode-ac-home* 
*sdl-scancode-ac-back* 
*sdl-scancode-ac-forward* 
*sdl-scancode-ac-stop* 
*sdl-scancode-ac-refresh* 
*sdl-scancode-ac-bookmarks* 
*sdl-scancode-brightnessdown* 
*sdl-scancode-brightnessup* 
*sdl-scancode-displayswitch* 
*sdl-scancode-kbdillumtoggle* 
*sdl-scancode-kbdillumdown* 
*sdl-scancode-kbdillumup* 
*sdl-scancode-eject* 
*sdl-scancode-sleep* 
*sdl-scancode-app1* 
*sdl-scancode-app2* 
*sdl-scancode-audiorewind* 
*sdl-scancode-audiofastforward* 
*sdl-scancode-softleft* 
*sdl-scancode-softright* 
*sdl-scancode-call* 
*sdl-scancode-endcall* 
*sdl-num-scancodes* 

*sdl-window-event-none* 
*sdl-window-event-shown* 
*sdl-window-event-hidden* 
*sdl-window-event-exposed* 
*sdl-window-event-moved* 
*sdl-window-event-resized* 
*sdl-window-event-changed* 
*sdl-window-event-minimized* 
*sdl-window-event-maximized* 
*sdl-window-event-restored* 
*sdl-window-event-enter* 
*sdl-window-event-leave* 
*sdl-window-event-focus-gained* 
*sdl-window-event-focus-lost* 
*sdl-window-event-close* 
*sdl-window-event-take-focus* 
*sdl-window-event-hit-test* 
*sdl-window-event-icc-prof-changed* 
*sdl-window-event-display-changed* 



;; libpixelformat.so 
;;pixelformat 
pixelformat2  
output-check
applyStretchedImage
size-int
sdl-upper-blit-scaled
  
*sdl-image-init-jpg*
*sdl-image-init-png*  
*sdl-image-init-tif*  
*sdl-image-init-webp* 
*sdl-image-init-jxl*  
*sdl-image-init-avif* 

%img-init
%img-load
image-load  
image-init
%sdl-create-renderer

surface-pixelformat-format
surface-pixelformat
surface-pixels  
surface-width
surface-height
surface-pitch

sdl-set-render-draw-color
show-rect

*sdl-renderer-software* 
*sdl-renderer-accelerated* 
*sdl-renderer-present-vsync* 
*sdl-renderer-target-texture* 
  
create-renderer
  
ttf-init
ttf-quit
ttf-render-text-solid
ttf-render-utf8-blended-wrapped
ttf-open-font
ttf-close-font

;; some cairo stuff - not sure it works yet

*cairo-format-rgb24* ;; ??
*cairo-format-argb32*


cairo-format-stride-for-width
cairo-image-surface-create

cairo-image-surface-create-for-data
cairo-rectangle
cairo-set-source-rgb
cairo-set-source-rgba
cairo-create
cairo-fill
cairo-surface-flush

cairo-set-line-width
cairo-stroke
cairo-arc
cairo-line-to
cairo-destroy
cairo-version-string
))

(use-modules (system foreign-library)) ;; probably only need system foreign
(use-modules (system foreign))


