;; autogenerated file from documentation sdl.org file via emacs

(define-module (graphics sdl2 image)
  #:export (

	    *init-jpg*
	    *init-png*
	    *init-tif*
	    *init-webp*
	    *init-jxl*
	    *init-avif*
	    
	    init
	    quit
	    load
	    
	    ))



(use-modules (system foreign-library)) ;; probably only need system foreign
(use-modules (system foreign))


(define *init-jpg*  #x00000001)
(define *init-png*  #x00000002)
(define *init-tif*  #x00000004)
(define *init-webp* #x00000008)
(define *init-jxl*  #x00000010)
(define *init-avif* #x00000020)

(define init
   (foreign-library-function "libSDL2_image" "IMG_Init" 
     #:return-type int       #:arg-types (list int)))

(define quit
  (foreign-library-function "libSDL2_image" "IMG_Quit"
                            #:return-type void
                            #:arg-types (list )))

(define load
   (foreign-library-function "libSDL2_image" "IMG_Load" 
     #:return-type '*       #:arg-types (list '* )))
